# Generated by Django 4.0.5 on 2022-07-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='picture_default.jpg', upload_to='profile_pics'),
        ),
    ]
