# Generated by Django 4.0.5 on 2022-06-30 07:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField()),
                ('rating', models.FloatField(default=0)),
                ('describtion', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('sellingStore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.store')),
            ],
        ),
    ]
